# Generated by Django 3.2.3 on 2022-01-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=125)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField(max_length=125)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
